GEOCODE_API_CODE = '78dbcd62-57ce-4e92-a0ba-c144a40552bf'
YANDEX_WEATHER_API_CODE = '4a668dba-9b87-4db8-932f-b50496803e4c'
WEATHER_VALUES = {'clear': 'Clear',
                          'partly-cloudy': 'Partly cloudy',
                          'cloudy': 'Cloudy',
                          'overcast': 'Overcast',
                          'partly-cloudy-and-light-rain': 'Light rain',
                          'partly-cloudy-and-rain': 'Rain',
                          'overcast-and-rain': 'Heavy rain',
                          'overcast-thunderstorms-with-rain': 'Thunderstorms',
                          'cloudy-and-light-rain': 'Light rain',
                          'overcast-and-light-rain': 'Light rain',
                          'cloudy-and-rain': 'Rain',
                          'overcast-and-wet-snow': 'Rain with snow',
                          'partly-cloudy-and-light-snow': 'Light snow',
                          'partly-cloudy-and-snow': 'Snow',
                          'overcast-and-snow': 'Snowfall',
                          'cloudy-and-light-snow': 'Light snow',
                          'overcast-and-light-snow': 'Light snow',
                          'cloudy-and-snow': 'Snow'}
